"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, UserPlus, FileText, Check } from "lucide-react";
import { BillForm, type BillingEnrollment } from "./bill-form";
import { RecordForm } from "./record-form";
type Course = { id: string; name: string; monthlyFee: string; fullFee: string };
export function BillingWorkspace({ enrollments, parents, courses, canPay, canIntake, canParent, canCourse, initialEnrollment, initialPeriod }: { enrollments: BillingEnrollment[]; parents: { id: string; name: string; mobile: string }[]; courses: Course[]; canPay: boolean; canIntake: boolean; canParent: boolean; canCourse: boolean; initialEnrollment?: string; initialPeriod?: string }) {
  const router = useRouter(); const [mode, setMode] = useState(enrollments.length || !canIntake ? "existing" : "new"); const [step, setStep] = useState(0);
  const [parentId, setParentId] = useState(parents.length ? parents[0].id : ""); const [newParent, setNewParent] = useState(!parents.length && canParent); const [parent, setParent] = useState<Record<string, string>>({});
  const [courseId, setCourseId] = useState(courses[0]?.id ?? ""); const [plan, setPlan] = useState("MONTHLY"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const course = courses.find(item => item.id === courseId);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return;
    const fields = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>;
    if (step === 0) { setParent(fields); setStep(1); setError(""); return; }
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/billing/intake", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ parentId: newParent ? "" : parentId, ...(newParent ? { parent } : {}), student: { ...fields, scholarship: "0", discount: "0", billingDay: "1", dueDay: "10" } }) });
      const result = await response.json();
      if (!response.ok) { setError(result.error ?? "Unable to save student details."); return; }
      router.push(`/billing?enrollment=${result.enrollmentId}`); router.refresh();
    } catch { setError("Unable to connect. Your invoice has not been generated."); } finally { setBusy(false); }
  }
  return <div className="billing-workspace"><div className="billing-mode" role="group" aria-label="Student selection"><button className={mode === "existing" ? "selected" : ""} onClick={() => setMode("existing")}><FileText size={17} />Existing enrollment</button>{canIntake && <button className={mode === "new" ? "selected" : ""} onClick={() => setMode("new")}><UserPlus size={17} />New student</button>}</div>
    {mode === "existing" ? enrollments.length ? <BillForm key={initialEnrollment ?? "existing"} enrollments={enrollments} canPay={canPay} initialEnrollment={initialEnrollment} initialPeriod={initialPeriod} /> : <div className="collection-empty"><h3>No active enrollments yet</h3>{canIntake && <button className="primary-button" onClick={() => setMode("new")}><UserPlus size={17} />Add a student</button>}<Link href="/enrollments">Enroll an existing student in a course</Link></div> : <>
      <ol className="billing-steps"><li className={step === 0 ? "current" : "complete"}><span>{step > 0 ? <Check size={13} /> : "1"}</span>Parent</li><li className={step === 1 ? "current" : ""}><span>2</span>Student & course</li><li><span>3</span>Review bill</li></ol>
      <form className="form-stack billing-intake" onSubmit={submit} key={step}><div className="section-heading"><h2>{step === 0 ? "Who is the parent?" : "Student & course"}</h2><span className="quiet-label">Step {step + 1} of 3</span></div>
        {step === 0 ? <>{canParent && <label className="check-field"><input type="checkbox" checked={newParent} onChange={event => setNewParent(event.target.checked)} />Add a new parent</label>}{newParent ? <div className="record-grid"><label className="field">Parent name<input name="name" required minLength={2} maxLength={100} defaultValue={parent.name} autoComplete="name" /></label><label className="field">Mobile number<input name="mobile" required type="tel" defaultValue={parent.mobile} autoComplete="tel" /></label><label className="field">WhatsApp number (optional)<input name="whatsapp" type="tel" defaultValue={parent.whatsapp} /></label><label className="field">Email (optional)<input name="email" type="email" defaultValue={parent.email} autoComplete="email" /></label><label className="field full-width">Billing address<input name="address" required minLength={5} maxLength={500} defaultValue={parent.address} autoComplete="street-address" /></label></div> : <label className="field">Parent<select required value={parentId} onChange={event => setParentId(event.target.value)}><option value="">Choose parent</option>{parents.map(item => <option key={item.id} value={item.id}>{item.name} / {item.mobile}</option>)}</select></label>}</> : <div className="record-grid"><label className="field">Student name<input name="name" required minLength={2} maxLength={100} /></label><label className="field">Date of birth (optional)<input type="date" name="dateOfBirth" max={new Date().toISOString().slice(0, 10)} /></label><label className="field">Course<select required name="courseId" value={courseId} onChange={event => setCourseId(event.target.value)}><option value="">Choose course</option>{courses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field">Payment plan<select name="paymentPlan" value={plan} onChange={event => setPlan(event.target.value)}><option value="MONTHLY">Monthly</option><option value="ONE_TIME">One-time / Full course</option></select></label><label className="field">Course fee (INR)<input name="fee" key={`${courseId}:${plan}`} type="number" min="0" step="0.01" required defaultValue={plan === "MONTHLY" ? course?.monthlyFee ?? "0" : course?.fullFee ?? "0"} /></label><label className="field">Enrollment date<input name="enrollmentDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label></div>}
        {error && <p role="alert" className="notice error">{error}</p>}<div className="billing-form-actions">{step > 0 && <button type="button" className="secondary-button" onClick={() => setStep(0)}><ArrowLeft size={16} />Back</button>}<button className="primary-button" disabled={busy || (step === 1 && !course)}>{busy ? "Saving..." : step === 0 ? "Continue" : "Save student & review fees"}<ArrowRight size={16} /></button></div>
      </form>{step === 1 && canCourse && <details className="inline-setup"><summary>Add a course</summary><RecordForm kind="courses" destination="/billing" fields={[{ name: "name", label: "Course name", required: true }, { name: "duration", label: "Duration (months)", type: "number", required: true, value: "6" }, { name: "monthlyFee", label: "Monthly fee (INR)", type: "number", required: true }, { name: "fullFee", label: "Full course fee (INR)", type: "number", required: true }]} /></details>}
    </>}<div className="billing-shortcuts"><Link href="/enrollments">Manage existing student enrollments <ArrowRight size={14} /></Link></div>
  </div>;
}