"use client";
import { useState } from "react";
import Link from "next/link";
import { MessageCircle, ArrowUpRight, CheckCircle2, Search } from "lucide-react";
import type { CollectionRow } from "@/lib/billing/collections";
import { PaymentStatus } from "./payment-status";
const tabs = [{ key: "week", label: "Next 7 days" }, { key: "today", label: "Due today" }, { key: "overdue", label: "Overdue" }, { key: "paid", label: "Paid" }, { key: "all", label: "All" }];
export function CollectionsPanel({ rows, today, canBill, canSend, initial = "week" }: { rows: CollectionRow[]; today: string; canBill: boolean; canSend: boolean; initial?: string }) {
  const [tab, setTab] = useState(tabs.some(item => item.key === initial) ? initial : "week"); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  function matches(row: CollectionRow, key: string) { return key === "all" || (key === "week" ? row.status === "week" || row.status === "today" : row.status === key); }
  const filtered = rows.filter(row => matches(row, tab) && `${row.student} ${row.parent} ${row.number}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="collections-section"><div className="section-heading"><div><p className="eyebrow">Fee follow-ups</p><h2>Collections & reminders</h2></div><span className="quiet-label">India time</span></div>
    <div className="collection-tools"><div className="collection-tabs" role="tablist" aria-label="Payment status">{tabs.map(item => <button key={item.key} id={`tab-${item.key}`} role="tab" aria-selected={tab === item.key} aria-controls="collection-results" onClick={() => { setTab(item.key); setPage(1); }} className={`collection-tab ${item.key}`}><span>{item.label}</span><b>{rows.filter(row => matches(row, item.key)).length}</b></button>)}</div><label className="collection-search"><Search size={16} /><input aria-label="Find student or parent" placeholder="Find student or parent" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /></label></div>
    <div id="collection-results" role="tabpanel" aria-labelledby={`tab-${tab}`}><div className="collection-list">{filtered.slice((page - 1) * 8, page * 8).map(row => <article className={`collection-row status-${row.status}`} key={row.id}>
      <div className="student-cell"><span className="student-avatar" aria-hidden="true">{row.student.split(" ").slice(0, 2).map(part => part[0]).join("")}</span><div><strong>{row.student}</strong><span>{row.course}</span><small>{row.number}</small></div></div>
      <div className="recipient-cell"><small>Parent / WhatsApp</small><strong>{row.parent}</strong><span>{row.phone || "No number saved"}</span></div>
      <div className="due-cell"><PaymentStatus dueDate={row.dueDate} today={today} settled={row.settled} partial={row.partial} /><span>{new Date(row.dueDate).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" })}</span></div>
      <div className="amount-cell"><strong>{new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(row.amount))}</strong><small>{row.settled ? "Paid in full" : row.invoiceId ? "Outstanding" : "Scheduled fee"}</small></div>
      <div className="collection-actions">{row.whatsapp ? <a className="whatsapp-button" href={row.whatsapp} target="_blank" rel="noopener noreferrer" title={`Open WhatsApp reminder for ${row.parent}`}><MessageCircle size={17} />Remind</a> : !row.settled && canSend ? <span className="quiet-label">Add valid number</span> : null}{row.invoiceId ? <Link className="icon-button" href={`/invoices/${row.invoiceId}`} aria-label={`View ${row.number}`} title="View invoice"><ArrowUpRight size={19} /></Link> : canBill ? <Link className="secondary-button" href={`/billing?enrollment=${row.enrollmentId}&period=${row.period}`}>Create bill</Link> : null}</div>
    </article>)}</div>{!filtered.length && <div className="collection-empty"><CheckCircle2 size={30} /><h3>{search ? "No matches" : tab === "week" ? "No fees due in the next 7 days" : tab === "overdue" ? "No overdue balances" : "Nothing here yet"}</h3>{canBill && !rows.length && <Link className="primary-button" href="/billing">Create your first bill <ArrowUpRight size={16} /></Link>}</div>}</div>
    {filtered.length > 8 && <div className="pagination"><button className="secondary-button" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>{page} / {Math.ceil(filtered.length / 8)}</span><button className="secondary-button" disabled={page * 8 >= filtered.length} onClick={() => setPage(page + 1)}>Next</button></div>}
  </section>;
}